### ISSUE TITLE
.update() should get the try to get the current rev and use it 

### ISSUE THREAD

**Issue by Nicktho** [Prismatik/auth-driver#7]

**Comment by davidbanham** [comment]
The point of the rev token is that it says "I want to change this document, and I can prove that I know what I'm changing it _from_" and works in a distributed environment. It's a way of catching whether or not someone else has changed the record between when you fetched it and when you sought to update it.

If you have the driver just grab whatever the rev is and then try to save the changes you're trying to make without giving the user/code the opportunity to inspect the sanity of that change, we're defeating the purpose of the rev.

Take a look at the "Understanding Revisions" heading in this doc:

http://writing.jan.io/2013/12/19/understanding-couchdb-conflicts.html

**Comment by Nicktho** [comment]
Duh! I was just testing you :eyes:
