### ISSUE TITLE
Support browsers (and transpile from ES2015)

### ISSUE THREAD

**Issue by Nicktho** [Prismatik/auth-driver#8]
Would be nice if this library worked isomorphically, we can also use this as an excuse to transpile ES2015 and take advantage of all the nice features babel gives us.

**Comment by Nicktho** [comment]
Axios is already a step towards the right direction, did not notice https://github.com/Prismatik/auth-driver/pull/5

**Comment by davidbanham** [comment]
That's just waiting on a reviewer to land.

You could be that reviewer!

**Comment by nwinch** [comment]
I reviewed #5 a while back.  I believe just a couple of suggestions were
left from what I could see.  Those comments have been wiped with rebase, so
I'll re-add now.  Nick feel free to review.

**Comment by nwinch** [comment]
Resolved by #10
